### ISSUE TITLE
How to pass as argument a globally-defined component imported from a third party package?

### ISSUE THREAD

**Issue by Ju01110101** [pearofducks/mount-vue-component#13]
Hi, I'm trying to use this neat utility with the component provided by that plugin: https://github.com/highlightjs/vue-plugin. That component is imported thus:

```
import hljsVuePlugin from '@highlightjs/vue-plugin'
app.use(hljsVuePlugin)
```

My issue is that when doing `const { vNode, destroy, el } = mount(comp, { props: { name: 'world' } })`, `comp` must be defined but if I replace `comp` with `hljsVuePlugin` Vue complains that `hljsVuePlugin` is not defined. Any idea how to solve this issue?

Also I have a hard time understanding how to pass values for the `children`, `element` and `app` arguments. Could you give a complete example where all those things are passed to the `mount()` function please? Thanks!

**Comment by pearofducks** [comment]
https://github.com/pearofducks/mvc-13-example

Here's an example of mounting that plugin to a specified DOM element. You can refer to the tests for examples of using the other attributes - but they're usually reserved for more advanced use cases.
