### ISSUE TITLE
Can this mount vuetify and/or custom Vue Components?

### ISSUE THREAD

**Issue by chirstius** [pearofducks/mount-vue-component#15]
I have a custom wrapper around a Vuetify vCard - I can't seem to figure out how to get it mounted using this module - is that even possible? Or will it only do standard Vue components?

I import the custom component, define it, but when trying to mount it:

![image](https://github.com/pearofducks/mount-vue-component/assets/1963688/9d2db0d5-4668-476a-b1d6-5db2a1905c19)

Any help is welcome, I might just be doing something stupid - if this can be done, can you provide a simple sample of how to mount a custom component? Thanks!

**Comment by pearofducks** [comment]
It can mount any Vue components. Vuetify often references context via injection, so it's necessary to provide the `appContext` for it to work.

https://github.com/pearofducks/mvc-vuetify-use-example
