### ISSUE TITLE
How to apend to some element?

### ISSUE THREAD

**Issue by Exlord** [pearofducks/mount-vue-component#4]
Hi, tanks for the great code , been looking for this for 2 days.
I managed to get it working by this 

```
    const { vNode, destroy, el } = mountComponent(BaseToast);
    container.appendChild(el?.childNodes[0] as Node);
```

Is this the correct approach ?  `container` is just a plain element.

**Comment by pearofducks** [comment]
Hi!

As mentioned [here](https://github.com/pearofducks/mount-vue-component#mountcomponent--props-children-element-app-), you can actually provide the `mount` export with an options object.

So in your example you could do:

```
const { vNode, destroy, el } = mountComponent(BaseToast, { element: container });
```

And that will mount `BaseToast` into the `container` element

**Comment by Exlord** [comment]
Yes but that would also remove ay other child component from the container ...
But I need to add multiple Toast components to the container!

**Comment by pearofducks** [comment]
Then what you posted would work fine :)

**Comment by Exlord** [comment]
Tanks for quick response, one more question, how can I pass an event listener to the component?

**Comment by pearofducks** [comment]
You could pass a callback via a prop, but otherwise I'm not sure without knowing more about your usecase. The Vue Discord chat might be able to help you more with that specific usecase.

**Comment by Exlord** [comment]
Tanks very much, I figured it out 

```
    const onClosed = ($event: Event) => {
      console.log("closed");
    };
    const props: any = { content, type, icon: options.icon, onClosed };
    const { vNode, destroy, el } = mountComponent(BaseToast, { props });
```
