### ISSUE TITLE
Can't call mount function in setup

### ISSUE THREAD

**Issue by colgin** [pearofducks/mount-vue-component#5]
[related issue](https://github.com/vuejs/vue-next/issues/3900)

Invoke render function in setup make currentInstance wrong.

**Comment by pearofducks** [comment]
Hi, can you elaborate? This isn't enough to be considered a reproduction, and the issue you're saying is related doesn't appear to involve this plugin at all.

**Comment by colgin** [comment]
sorry for that, [reproduction](https://codesandbox.io/s/weathered-violet-b01p8?file=/src/components/HelloWorld.vue)

In this demo, after mount was called, getCurrentInstance return wrong value. In related issue above, I was told that call render manually in setup is not allowed(In your [source code](https://github.com/pearofducks/mount-vue-component/blob/8f01ba4375c37ff71be9c39719486d0a61376ebc/index.js#L9), you use render function). So it broken.

**Comment by pearofducks** [comment]
Gotcha, thanks for expanding the description.

As mentioned in the Vue issue, this is a WONTFIX as it isn't allowed by Vue itself. This module calls `render`, and nested `render`s aren't allowed in `setup` by Vue's design.
