### ISSUE TITLE
Usage with appendChild

### ISSUE THREAD

**Issue by agritheory** [pearofducks/mount-vue-component#6]
This example taken from [here](https://css-tricks.com/creating-vue-js-component-instances-programmatically/). I've used this technique successfully in Vue 2 but cannot seem to get it to work with this package.

```js
import Button from 'Button.vue'
import Vue from 'vue'
var ComponentClass = Vue.extend(Button)
var instance = new ComponentClass({
    propsData: { type: 'primary' }
})
instance.$mount() // pass nothing
this.$refs.container.appendChild(instance.$el)
```

As I understand the design, this should work.

```js 
import Button from "./components/Button.vue";
import { mount } from "mount-vue-component";

import { ref, defineComponent, onMounted } from "vue";

export default defineComponent({
  name: "App",
  setup(props, context) {
    const container = ref(null);

    onMounted(() => {
      console.log(container.value);
      var instance = mount(Button, { props: { type: "primary" } });
      container.value.appendChild(instance);
    });
    return { container };
  },
});
```
[reproduction case](https://codesandbox.io/s/billowing-night-28ug6?file=/src/App.vue)

**Comment by pearofducks** [comment]
That should not work, you've misinterpreted the return signature of `mount`. `mount` returns an object, one attribute of which is `el` that can be used in DOM operations.

Calling `mount` in `setup` is also known to be a bit flaky because of how Vue 3 is designed - but that's outside of your core issue here.
