### ISSUE TITLE
parent property of VNode and Component are not set

### ISSUE THREAD

**Issue by muelphil** [pearofducks/mount-vue-component#7]
Using the `mount` function will not set the `parent` property of the VNode and the component. It is possible to adjust the function to set those, however you can only set the `parent` property of the component after the `render` function is called. If the parent of the component is required in the `setup` function this will still result in errors, as the `setup` will be called during the `render` function call. An example for when it is required is when using the Provide/Inject-API.

I don't believe this can be solved programatically, but the workaround I found was simply using the builtin `<component :is="...">` with the `is`-prop. I found out, that the is prop will not only take names of registered functions but also components that are not previously registered and render them. This resolved all my problems and is generally easier to use than manually mounting and destroying components.

**Comment by pearofducks** [comment]
Generally components mounted using this utility _shouldn't_ have a `parent`. I'm not sure what your usecase is, but it sounds like this module isn't the best fit.

If you already have a parent component, it's generally not difficult to mount a child component, even if you need to mount it to another DOM element (e.g. something teleport-ish). This module is usually used for things like singletons (e.g. a Toast component) that could be mounted by the top-level component, but that'd imply a lot more userland burden.
