### ISSUE TITLE
Allow prop type to be inferred

### ISSUE THREAD

**Issue by mkbctrl** [pearofducks/mount-vue-component#9]
Hey, I tried to create PR, but I failed, no access. Maybe I am too dumb to do it properly xD

Here's a suggestion to improve your TS:

```
export function mount<TProps>(component: Component, { props, children, element, app }?: {
    props?: TProps;
    children?: unknown;
    app?: App;
    element?: HTMLElement;
}): MountResult;
```
Solves the following issue:
![Screenshot 2022-06-10 at 12 29 45](https://user-images.githubusercontent.com/10107362/173047925-859db26a-e1c8-423e-880b-88f047ff8352.png)

And allows the props to be dynamically infered by TS, no need to pass any additional interfaces:

with infer:
![Screenshot 2022-06-10 at 12 38 10](https://user-images.githubusercontent.com/10107362/173048143-698403b2-7c93-4e42-8a3e-b597f540f945.png)

without infer:
![Screenshot 2022-06-10 at 12 38 29](https://user-images.githubusercontent.com/10107362/173048172-e514b887-b27d-4948-8285-ce75667cdb26.png)

**Comment by pearofducks** [comment]
Thanks for taking time to submit this and describe the issue!
